config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :support_tickets

  root 'support_tickets#index'
end

app/models/support_ticket.rb
class SupportTicket < ApplicationRecord
  include AASM

  require 'csv'

  has_many :active_admin_comments, as: :resource, class_name: "ActiveAdmin::Comment"

  belongs_to :user, optional: true

  validates :requester_email, format: { with: Devise.email_regexp }, unless: :has_user?
  validates :requester_name, presence: true, unless: :has_user?

  validates :subject, presence: true
  validates :content, presence: true

  scope :new_support_tickets, -> { where(status: 'new') }
  scope :pending_support_tickets, -> { where(status: 'pending') }
  scope :resolved_support_tickets, -> { where(status: 'resolved') }

  aasm column: :status do
    state :new, initial: true
    state :pending
    state :resolved

    event :set_state do
      transitions from: :new, to: :pending, if: :is_pending?
    end

    event :resolve do
      transitions from: :pending, to: :resolved
    end
  end

  def has_user?
    !self.user.nil?
  end

  def is_pending?
    # TODO: check if has comments
    self.active_admin_comments.count > 0
  end

  def dump_to_csv
    ret = false
    cfs = CsvFileStore.get_csv_file_store

    cfs.with_lock do
      begin
        cfs.lock_csv_file('a+') do |f|
          line_count = f.readlines.size
          # puts "SIZE: #{line_count}"
          if line_count == 0
            dump_csv_headers(f)
          end

          dump_csv_values(f)
        end

        ret = true
      rescue
      end
    end

    ret
  end

  # Imports new support tickets from csv
  # @returns: number of imported or found tickets
  def self.import_new_tickets(count_only = false)
    imported_count = 0
    cfs = CsvFileStore.get_csv_file_store

    cfs.with_lock do
      failed_rows = []
      file_opened = false

      begin
        cfs.lock_csv_file('a+') do |f| # lock for write so we're exclusive
          file_opened = true
          csv = CSV.parse(f, headers: true)

          if count_only
            imported_count = csv.count
          else
            csv.each_with_index do |row, i|
              st = SupportTicket.new(row.to_hash)
              if st.save
                imported_count += 1
              else
                failed_rows.push(row)
              end
            end
          end
        end
      rescue Exception => e
        Rails.logger.debug(e)
      end

      if !count_only && file_opened
        cfs.truncate!
        unless failed_rows.blank?
          cfs.lock_csv_file('a+') do |f|
            st = SupportTicket.new
            st.dump_csv_headers(f)
            failed_rows.each do |csv_row|
              f << csv_row
            end
          end
        end
      end
    end

    return imported_count
  end

  def dump_csv_headers(file)
    file << (exported_attributes.keys).join(',') + "\n"
  end

private

  def exported_attributes
    self.attributes.except("id", "status", "updated_at")
  end

  def dump_csv_values(file)
    if self.new_record?
      now = Time.now
      self.created_at = self.updated_at = now
    end
    file << (exported_attributes.values.collect{ |c| get_csv_field_string(c) }).join(',') + "\n"
  end

  def get_csv_field_string(value)
    value = begin
      # ActionController::Base.helpers.strip_tags(value.to_s)
      ActionView::Base.full_sanitizer.sanitize(value.to_s)
    rescue
      raise "Cannot sanitize value!"
    end

    value = value.gsub('"','\"')

    ['"', value, '"'].reject{|r| r.nil?}.join
  end

  # def self.lock_csv_file(openmode = 'r', lockmode = nil)
  #   filename = SUPPORT_TICKETS_CSV_PATH

  #   if openmode == 'r' || openmode == 'rb'
  #     lockmode ||= File::LOCK_SH
  #   else
  #     lockmode ||= File::LOCK_EX
  #   end

  #   value = nil

  #   open(filename, openmode) do |f|
  #     SupportTicket.flock(f, lockmode) do
  #       begin
  #         value = yield f
  #       ensure
  #         f.flock(File::LOCK_UN)
  #       end
  #     end

  #     return value
  #   end
  # end

  # def self.flock(file, mode)
  #   success = file.flock(mode)
  #   if success
  #     begin
  #       yield file
  #     ensure
  #       file.flock(File::LOCK_UN)
  #     end
  #   end

  #   return success
  # end

end

app/controllers/support_tickets_controller.rb
class SupportTicketsController < ApplicationController

  # cancan
  load_and_authorize_resource # param_method: :support_ticket_params

  USER_METHODS = [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: USER_METHODS
  before_action :set_support_ticket, only: USER_METHODS


  # GET /support_tickets
  # GET /support_tickets.json
  def index
    @support_tickets = current_user.nil? ? nil : current_user.support_tickets
    @logged_in_user = current_user.nil? ? nil : current_user.id
  end

  # GET /support_tickets/1
  # GET /support_tickets/1.json
  def show
  end

  # GET /support_tickets/new
  def new
    if current_user.nil?
      @support_ticket = SupportTicket.new
    else
      @support_ticket = current_user.support_tickets.new
      @logged_in_user = current_user.id
    end
  end

  # GET /support_tickets/1/edit
  def edit
  end

  # POST /support_tickets
  # POST /support_tickets.json
  def create
    @support_ticket = SupportTicket.new(support_ticket_params)

    respond_to do |format|
      if @support_ticket.dump_to_csv
        format.html { redirect_to new_support_ticket_path, notice: 'Support ticket was successfully created.' }
        # format.json { render :show, status: :created, location: @support_ticket }
      else
        flash[:alert] = "Form was sent with invalid values."
        format.html { render :new }


          # error: 'Form has invalid fields. Please correct them and try again.' }
        # format.json { render json: @support_ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /support_tickets/1
  # PATCH/PUT /support_tickets/1.json
  def update
    respond_to do |format|
      if @support_ticket.update(support_ticket_params)
        format.html { redirect_to @support_ticket, notice: 'Support ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @support_ticket }
      else
        format.html { render :edit }
        format.json { render json: @support_ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /support_tickets/1
  # DELETE /support_tickets/1.json
  def destroy
    @support_ticket.destroy
    respond_to do |format|
      format.html { redirect_to support_tickets_url, notice: 'Support ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support_ticket
      @support_ticket = SupportTicket.find(params[:id])
      @logged_in_user = current_user.id
    end

    # Only allow a list of trusted parameters through.
    def support_ticket_params
      params.require(:support_ticket).permit(
        :requester_email,
        :requester_name,
        :status,
        :subject,
        :content,
        :user_id
      )
    end
end

app/views/support_tickets/_form.html.erb
<%= form_with(model: support_ticket, local: true) do |form| %>
  <% if support_ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(support_ticket.errors.count, "error") %> prohibited this support_ticket from being saved:</h2>

      <ul>
      <% support_ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @logged_in_user.nil? %>
    <div class="field">
      <%= form.label :requester_email %>
      <%= form.email_field :requester_email, required: true %>
    </div>

    <div class="field">
      <%= form.label :requester_name %>
      <%= form.text_field :requester_name, required: true %>
    </div>
  <% else %>
    <%= form.hidden_field :user_id %>
  <% end %>




  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, required: true %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 15, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/support_tickets/edit.html.erb
<h1>Editing Support Ticket</h1>

<%= render 'form', support_ticket: @support_ticket %>

<%= link_to 'Show', @support_ticket %> |
<%= link_to 'Back', support_tickets_path %>

app/views/support_tickets/index.html.erb
<p id="notice"><%= notice %></p>


<% unless @support_tickets.nil? %>
  <h1>Support Tickets</h1>
  <table>
    <thead>
      <tr>
        <th>Status</th>
        <th>Subject</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%  @support_tickets.each do |support_ticket| %>
        <tr>
          <td><%= support_ticket.status %></td>
          <td><%= support_ticket.subject %></td>
          <td><%= support_ticket.content %></td>
          <td><%= link_to 'Show', support_ticket %></td>
          <td><%= link_to 'Edit', edit_support_ticket_path(support_ticket) %></td>
          <td><%= link_to 'Destroy', support_ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%  end %>
    </tbody>
  </table>
<% end %>

<br>

<%= link_to 'New Support Ticket', new_support_ticket_path %>
<% if @logged_in_user.nil? %>
  <%= link_to 'Login', new_user_session_path %>
  <%= link_to 'Register', new_user_registration_path %>
<% else %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% end %>

app/views/support_tickets/new.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>New Support Ticket</h1>

<%= render 'form', support_ticket: @support_ticket %>

<%= link_to 'Back', support_tickets_path %>

app/views/support_tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @support_ticket.status %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @support_ticket.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @support_ticket.content %>
</p>

<%= link_to 'Edit', edit_support_ticket_path(@support_ticket) %> |
<%= link_to 'Back', support_tickets_path %>